import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase.js'
const blank={code:'',product_id:'',kind:'percent',value:'',expires_at:'',usage_limit:'',active:true}
export default function CouponsPage(){
 const [data,setData]=useState({coupons:[],products:[]}),[form,setForm]=useState(blank),[id,setId]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{const {data,error}=await supabase.rpc('admin_coupon_data');if(error)setError(error.message);else setData(data)}
 useEffect(()=>{load()},[])
 const update=(key,value)=>setForm(f=>({...f,[key]:value}))
 const edit=c=>{const d=c.expires_at?new Date(c.expires_at):null;setId(c.id);setForm({...c,product_id:c.product_id||'',usage_limit:c.usage_limit??'',expires_at:d?new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16):''});setMessage('');window.scrollTo({top:0,behavior:'smooth'})}
 const save=async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const payload={code:form.code.trim().toUpperCase(),product_id:form.product_id,kind:form.kind,value:Number(form.value),expires_at:form.expires_at?new Date(form.expires_at).toISOString():null,usage_limit:form.usage_limit===''?null:Number(form.usage_limit),active:form.active,min_order:0,max_discount:null,per_customer_limit:null};const {error}=id?await supabase.from('coupons').update(payload).eq('id',id):await supabase.from('coupons').insert(payload);if(error)throw error;setForm(blank);setId(null);setMessage('Coupon saved.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="admin-page"><div className="page-header"><div><h1>Coupons</h1><p>One code. One honey size.</p></div></div>{error&&<p role="alert" className="alert error">{error}</p>}{message&&<p role="status" className="alert success">{message}</p>}<section className="admin-card"><h2>{id?'Edit coupon':'Create coupon'}</h2><form onSubmit={save}><fieldset disabled={busy} className="form-grid"><label className="field">Code<input required pattern="[A-Za-z0-9_-]{3,24}" maxLength={24} value={form.code} onChange={e=>update('code',e.target.value.toUpperCase())}/></label><label className="field">Honey size<select required value={form.product_id} onChange={e=>update('product_id',e.target.value)}><option value="">Choose a size</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.size_label}</option>)}</select></label><label className="field">Discount type<select value={form.kind} onChange={e=>update('kind',e.target.value)}><option value="percent">Percentage</option><option value="fixed">Fixed amount (₹)</option></select></label><label className="field">{form.kind==='percent'?'Percentage':'Amount (₹)'}<input required type="number" min="0.01" step="0.01" max={form.kind==='percent'?100:99999999} value={form.value} onChange={e=>update('value',e.target.value)}/></label><label className="field">Expiry (optional, local time)<input type="datetime-local" value={form.expires_at} onChange={e=>update('expires_at',e.target.value)}/></label><label className="field">Usage limit (optional)<input type="number" min="1" step="1" value={form.usage_limit} onChange={e=>update('usage_limit',e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={form.active} onChange={e=>update('active',e.target.checked)}/>Active</label><div className="button-group"><button className="primary-btn">{busy?'Saving…':'Save coupon'}</button>{id&&<button type="button" className="secondary-btn" onClick={()=>{setId(null);setForm(blank)}}>Cancel</button>}</div></fieldset></form></section><section className="admin-card"><h2>Your coupons</h2><p className="muted-text">Uses include cancelled orders. Discounts exclude delivery. Empty limits mean unlimited.</p>{data.coupons.map(c=><div className="business-row" key={c.id}><div><strong>{c.code} · {c.kind==='percent'?`${c.value}%`:`₹${c.value}`}</strong><small>{data.products.find(p=>p.id===c.product_id)?.size_label||'Assign a size'} · {!c.active?'Inactive':c.expires_at&&new Date(c.expires_at)<=new Date()?'Expired':'Active'} · {c.uses} / {c.usage_limit??'Unlimited'} uses</small></div><button className="secondary-btn" onClick={()=>edit(c)}>Edit</button></div>)}{!data.coupons.length&&<p>No coupons yet.</p>}</section></div>
}
