import ProfitSummary from '../components/ProfitSummary.jsx'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { readAll } from '../lib/adminTools.js'
import { balance, cents, rupees } from '../lib/business.js'
import { currency, shortDate } from '../lib/format.js'
import StatusBadge from '../components/StatusBadge.jsx'
export default function DashboardPage(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(true)
 const load=useCallback(async()=>{setBusy(true);setError('');try{const [orders,payments,products,giveaways,expenses]=await Promise.all([readAll('orders','id,order_number,customer_name,status,subtotal,discount_amount,delivery_charge,grand_total,created_at,order_items(quantity,unit_cost)'),readAll('payments','id,order_id,kind,amount'),readAll('products'),readAll('stock_giveaways'),readAll('business_expenses')]);setData({orders:orders.sort((a,b)=>b.created_at.localeCompare(a.created_at)),payments,products,giveaways,expenses})}catch(e){setError(e.message)}finally{setBusy(false)}},[])
 useEffect(()=>{load()},[load])
 const rows=(data?.orders||[]).map(o=>({...o,...balance(o,data.payments)})),open=rows.filter(o=>!['Cancelled','Delivered'].includes(o.status)),due=rows.filter(o=>o.pending>0),refunds=rows.filter(o=>o.refundDue>0)
 const delivered=rupees(rows.filter(o=>o.status==='Delivered').reduce((s,o)=>s+cents(o.grand_total),0)),pending=rupees(due.reduce((s,o)=>s+cents(o.pending),0)),stock=(data?.products||[]).reduce((s,p)=>s+p.available_quantity,0)
 return <div className="admin-page overview-page"><div className="page-header"><div><div className="eyebrow">YOUR BUSINESS AT A GLANCE</div><h1>Overview</h1><p>Start a sale, collect a payment, or check what needs delivery.</p></div><button className="secondary-btn" onClick={load} disabled={busy}>{busy?'Refreshing…':'Refresh'}</button></div>
 {error&&<div role="alert" className="alert error">{error}</div>}
 {!data? <div className="admin-card">{busy?'Loading your business…':'Could not load records. Please retry.'}</div>:<>
 <ProfitSummary data={data}/><div className="overview-metrics">{[['Delivered sales',currency(delivered),'Completed orders, including delivery'],['Payments pending',currency(pending),due.length+' orders awaiting payment'],['To fulfil',open.length,'Orders still awaiting delivery'],['Stock available',stock+' jars','Across all honey sizes']].map(([title,value,note])=><article key={title}><span>{title}</span><strong>{value}</strong><small>{note}</small></article>)}</div>
 <div className="overview-grid"><section className="admin-card"><div className="section-heading"><div><h2>Next actions</h2><p>Keep your daily work moving.</p></div></div><div className="action-list"><Link to="/admin/orders?view=fulfil"><span><strong>Prepare and deliver orders</strong><small>New, confirmed, packed and shipped</small></span><b>{open.length} →</b></Link><Link to="/admin/orders?view=pending"><span><strong>Collect pending payments</strong><small>Open an order to record money received</small></span><b>{due.length} →</b></Link><Link to="/admin/orders?view=refund"><span><strong>Refund cancelled orders</strong><small>Money still held for cancelled sales</small></span><b>{refunds.length} →</b></Link></div></section>
 <section className="admin-card"><div className="section-heading"><div><h2>Stock check</h2><p>Record a purchase when new jars arrive.</p></div><Link to="/admin/products">View stock →</Link></div><div className="stock-mini">{data.products.map(p=><div key={p.id}><span>{p.size_label}<small>{p.active?'Available for sale':'Not active'}</small></span><strong className={p.available_quantity<=5?'low-stock':''}>{p.available_quantity} jars</strong></div>)}</div><Link className="secondary-btn" to="/admin/purchases">Add stock purchase</Link></section></div>
 <section className="admin-card"><div className="section-heading"><div><h2>Recent orders</h2><p>Delivery status and payment balance are shown separately.</p></div><Link to="/admin/orders">All orders →</Link></div><div className="order-cards">{rows.slice(0,6).map(o=><Link className="order-card" key={o.id} to={'/admin/orders/'+o.id}><div className="order-card-top"><span>{o.order_number}</span><StatusBadge status={o.status}/></div><h3>{o.customer_name}</h3><small>{shortDate(o.created_at)}</small><div className="order-card-bottom"><strong>{currency(o.grand_total)}</strong><span>{o.refundDue>0?'Refund due '+currency(o.refundDue):o.pending>0?'Due '+currency(o.pending):o.status==='Cancelled'?'Cancelled':'Paid'} →</span></div></Link>)}</div>{!rows.length&&<div className="empty-state"><h3>Your first sale starts here</h3><p>Add the customer, honey and payment in one guided flow.</p><Link className="primary-btn" to="/admin/new-sale">Create a sale</Link></div>}</section>
 </>}
 </div>
}
