import RecordEditor from '../components/RecordEditor.jsx'
import { useCallback, useEffect, useRef, useState } from 'react'
import { currency } from '../lib/format.js'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase.js'
import { readAll } from '../lib/adminTools.js'
import { giveawayRows, giveawayTotals, weightText, indiaDate } from '../lib/salesReport.js'
const empty={product_id:'',quantity:1,recipient:'',note:''}
export default function GiveawaysPage(){
 const [products,setProducts]=useState([]),[history,setHistory]=useState([]),[gift,setGift]=useState(empty),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[uncertain,setUncertain]=useState(false)
 const lock=useRef(false)
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [p,g]=await Promise.all([readAll('products'),readAll('stock_giveaways')]);setProducts(p);setHistory(g)}catch(e){setError(e.message)}finally{setLoading(false)}},[])
 useEffect(()=>{load()},[load])
 const rows=giveawayRows(history,{search}),total=giveawayTotals(rows),selected=products.find(p=>p.id===gift.product_id)
 const submit=async e=>{e.preventDefault();if(lock.current||uncertain)return;lock.current=true;setBusy(true);setError('');setMessage('');try{const {error}=await supabase.rpc('record_giveaway',{p_product_id:gift.product_id,p_quantity:Number(gift.quantity),p_recipient:gift.recipient.trim(),p_note:gift.note.trim()});if(error)throw error;setGift(empty);setMessage('Free honey recorded. Stock has been reduced.');await load()}catch(e){setError(e.message);if(!e.code||!/^P\d|^22|^23/.test(e.code))setUncertain(true)}finally{setBusy(false);lock.current=false}}
 return <div className="admin-page"><div className="page-header"><div><div className="eyebrow">INVENTORY</div><h1>Free honey</h1><p>Record who received honey for free. Every entry also appears in your sales report.</p></div><Link className="secondary-btn" to="/admin/sales-report">View full report</Link></div>
 {error&&<p className="alert error" role="alert">{error}</p>}{message&&<p className="alert success" role="status">{message}</p>}
 {uncertain&&<div className="alert warning"><p>Confirmation was interrupted. Refresh and check the history before recording this gift again.</p><button className="secondary-btn" onClick={load} disabled={loading}>Refresh history</button><button className="secondary-btn" disabled={loading} onClick={()=>{setUncertain(false);setGift(empty)}}>I checked the history · start a new entry</button></div>}
 <div className="giveaway-layout"><section className="admin-card"><h2>Record a giveaway</h2><p className="muted-text">Customer pays ₹0. Stock decreases by the jars entered.</p><form onSubmit={submit}><fieldset disabled={busy||loading||uncertain}><label className="field"><span>Honey size</span><select required value={gift.product_id} onChange={e=>setGift({...gift,product_id:e.target.value})}><option value="">Choose size</option>{products.map(p=><option key={p.id} value={p.id} disabled={p.available_quantity<1}>{p.size_label} · {p.available_quantity} available</option>)}</select></label><label className="field"><span>Jars given free</span><input required type="number" min="1" step="1" max={selected?.available_quantity||0} value={gift.quantity} onChange={e=>setGift({...gift,quantity:e.target.value})}/></label><label className="field"><span>Given to</span><input required minLength="2" maxLength="100" placeholder="Person, shop or event" value={gift.recipient} onChange={e=>setGift({...gift,recipient:e.target.value})}/></label><label className="field"><span>Reason / note</span><input maxLength="500" placeholder="Gift or sample" value={gift.note} onChange={e=>setGift({...gift,note:e.target.value})}/></label><p className="muted-text">{selected?`Cost: ${currency(selected.cost_price)} / jar · Total giveaway cost ${currency(Number(selected.cost_price)*Number(gift.quantity))}`:'Choose a size to see its cost.'}</p>{selected&&Number(selected.cost_price)<=0&&<p className="alert warning">Set this honey’s cost in Products & Stock before recording a giveaway.</p>}<button className="primary-btn" disabled={!selected||Number(selected.cost_price)<=0}>{busy?'Recording…':'Save free honey entry'}</button></fieldset></form></section>
 <section className="admin-card"><div className="card-title-row"><div><h2>Giveaway history</h2><p>{total.jars} jars · {weightText(total)} · FREE</p></div><button className="secondary-btn" onClick={load} disabled={loading}>{loading?'Loading…':'Refresh'}</button></div><label className="field"><span>Find recipient</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or note"/></label><div className="table-wrap"><table><thead><tr><th>Date</th><th>Given to</th><th>Honey</th><th>Jars</th><th>Note</th><th>Actions</th></tr></thead><tbody>{rows.map(g=><tr key={g.id}><td>{indiaDate(g.created_at)}</td><td>{g.recipient}</td><td>{g.size_label}</td><td>{g.jars}</td><td>{g.note||'—'}</td><td><RecordEditor kind="giveaway" record={history.find(r=>r.id===g.id)} onSaved={load}/></td></tr>)}{!rows.length&&!loading&&<tr><td colSpan="6" className="empty-cell">No matching free honey entries.</td></tr>}</tbody></table></div></section></div></div>
}
