import { createContext, useContext, useEffect, useRef, useState } from 'react'
import { Link, NavLink, Navigate, Outlet, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase.js'
import { currency, shortDate } from '../lib/format.js'

const couponMessage = message => /coupon/i.test(message || '') ? ('Invalid coupon. ' + (/not in your cart|different honey size/i.test(message) ? 'This code does not apply to the sizes in your cart.' : /usage limit|already used/i.test(message) ? 'This code has reached its usage limit.' : /expired|inactive/i.test(message) ? 'This code is unavailable or expired.' : 'Please check the code and try again.')) : message;
const Auth=createContext(null)
export function AuthProvider({children}){
 const [session,setSession]=useState(undefined),[admin,setAdmin]=useState(false)
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((event,s)=>setSession(s));return ()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{let live=true;setAdmin(false);if(session?.user) supabase.from('profiles').select('role').eq('id',session.user.id).single().then(({data})=>{if(live)setAdmin(data?.role==='admin')});return()=>{live=false}},[session?.user.id])
 return <Auth.Provider value={{session,admin}}>{children}</Auth.Provider>
}
export function Login(){
 const {session}=useContext(Auth),[signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 if(session) return <Navigate to="/shop" replace/>
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');const f=new FormData(e.currentTarget);try{const credentials={email:f.get('email').trim(),password:f.get('password')};const {data,error}=signup?await supabase.auth.signUp({...credentials,options:{emailRedirectTo:window.location.origin+'/shop'}}):await supabase.auth.signInWithPassword(credentials);if(error)throw error;if(signup&&!data.session)setMessage('Check your email to confirm your account, then log in.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY) return <main className="auth-wrap"><div className="auth-card"><h1>Almost ready.</h1><p>Add your Supabase connection in the project’s .env file to enable login and ordering. Setup instructions are in README.md.</p></div></main>
 return <main className="auth-wrap"><div className="auth-card"><div className="brand-mark">H</div><p className="eyebrow">PURE HONEY</p><h1>{signup?'A little sweetness awaits.':'Welcome back.'}</h1><p>Log in to shop and keep track of your orders.</p><form onSubmit={submit}><label className="field">Email<input autoComplete="email" name="email" type="email" required/></label><label className="field">Password<input autoComplete={signup?'new-password':'current-password'} name="password" type="password" minLength={8} required/></label>{error&&<p role="alert" className="alert error">{error}</p>}{message&&<p role="status" className="alert success">{message}</p>}<button className="primary-btn" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Log in'}</button></form><button className="text-btn" onClick={()=>{setSignup(!signup);setError('');setMessage('')}}>{signup?'Already registered? Log in':'New here? Create an account'}</button></div></main>
}
export function CustomerLayout(){const {session,admin}=useContext(Auth);if(session===undefined)return <p className="loading">Loading…</p>;if(!session)return <Navigate to="/login" replace/>;return <><header className="store-header"><Link className="brand-lockup" to="/shop"><span className="brand-mark">H</span><strong>Pure Honey</strong></Link><nav><NavLink to="/shop">Shop</NavLink><NavLink to="/orders">My Orders</NavLink>{admin&&<Link to="/admin">Admin</Link>}<button className="text-btn" onClick={()=>supabase.auth.signOut()}>Log out</button></nav></header><main className="store-main"><Outlet/></main></>}
export function Shop(){
 const [products,setProducts]=useState([]),[loading,setLoading]=useState(true),[cart,setCart]=useState({}),[details,setDetails]=useState({name:'',mobile:'',address:'',coupon:''}),[quote,setQuote]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const navigate=useNavigate(),request=useRef(crypto.randomUUID()),revision=useRef(0)
 useEffect(()=>{supabase.from('products').select('*').in('grams',[250,500,1000]).order('grams').then(({data,error})=>{if(error)setError(error.message);else setProducts(data||[]);setLoading(false)})},[])
 const invalidate=()=>{revision.current++;setQuote(null);setError('');request.current=crypto.randomUUID()}
 const change=(key,value)=>{invalidate();setDetails(d=>({...d,[key]:value}))}
 const setQuantity=(product,value)=>{invalidate();const quantity=Math.max(0,Math.min(100,product.available_quantity,Math.floor(Number(value)||0)));setCart(c=>{const next={...c};if(quantity===0)delete next[product.id];else next[product.id]=quantity;return next})}
 const items=products.filter(p=>cart[p.id]).map(p=>({product_id:p.id,quantity:cart[p.id]}))
 const review=async e=>{e.preventDefault();if(!items.length){setError('Add at least one honey size to your cart.');return}setBusy(true);setError('');const rev=revision.current;try{const {data,error}=await supabase.rpc('quote_cart',{p_items:items,p_mobile:details.mobile,p_coupon_code:details.coupon});if(error)throw error;if(rev===revision.current)setQuote(data)}catch(e){setError(couponMessage(e.message));setQuote(null)}finally{setBusy(false)}}
 const place=async()=>{setBusy(true);setError('');try{const {error}=await supabase.rpc('place_cart_order',{p_items:items,p_customer_name:details.name,p_mobile:details.mobile,p_address:details.address,p_coupon_code:details.coupon,p_request_id:request.current,p_expected_total:quote.grand_total});if(error)throw error;navigate('/orders',{state:{placed:true}})}catch(e){setError(couponMessage(e.message));setQuote(null)}finally{setBusy(false)}}
 return <><div className="shop-heading"><span className="eyebrow">SIMPLY GOOD HONEY</span><h1>Build your honey box.</h1><p>Add one, two or all three sizes to the same order.</p></div>{error&&<p className="alert error" role="alert">{error}</p>}{loading?<p>Loading honey…</p>:<div className="jar-grid">{products.map((p,i)=>{const qty=cart[p.id]||0;return <article key={p.id} className={'jar-card '+(qty?'selected':'')}><div className="jar-scene" aria-hidden="true"><div className={'honey-jar jar-'+i}><div className="jar-label">PURE<br/><b>HONEY</b><small>{p.size_label}</small></div></div></div><div className="jar-info"><h2>{p.size_label}</h2><strong>{currency(p.price)}</strong></div>{!p.active||p.available_quantity<1?<span>Out of stock</span>:<div className="cart-controls"><p className="stock-remaining">{p.available_quantity} jars left in stock</p><div className="cart-quantity"><button type="button" aria-label={`Remove one ${p.size_label}`} onClick={()=>setQuantity(p,qty-1)} disabled={!qty||busy}>−</button><input aria-label={`${p.size_label} quantity`} type="number" disabled={busy} min="0" max={Math.min(100,p.available_quantity)} value={qty} onChange={e=>setQuantity(p,e.target.value)}/><button type="button" aria-label={`Add one ${p.size_label}`} onClick={()=>setQuantity(p,qty+1)} disabled={busy||qty>=Math.min(100,p.available_quantity)}>+</button></div></div>}</article>})}</div>}{!loading&&!products.length&&<p>No products available. Please try again later.</p>}
 {items.length>0&&<section className="checkout panel"><div><span className="eyebrow">YOUR CART · {items.reduce((s,i)=>s+i.quantity,0)} JARS</span><h2>Delivery details.</h2><div className="cart-lines">{products.filter(p=>cart[p.id]).map(p=><div key={p.id}><span>{p.size_label} × {cart[p.id]}</span><strong>{currency(p.price*cart[p.id])}</strong></div>)}</div><form onSubmit={review}><fieldset disabled={busy}><label className="field">Customer name<input required minLength={2} maxLength={100} autoComplete="name" value={details.name} onChange={e=>change('name',e.target.value)}/></label><label className="field">Mobile number<input required type="tel" inputMode="numeric" pattern="[0-9]{10}" maxLength={10} autoComplete="tel-national" placeholder="10-digit mobile number" value={details.mobile} onChange={e=>change('mobile',e.target.value)}/></label><label className="field">Full delivery address<textarea required minLength={10} maxLength={500} rows={3} autoComplete="street-address" placeholder="House, street, city, state and PIN code" value={details.address} onChange={e=>change('address',e.target.value)}/></label><label className="field">Coupon code <span className="optional">(optional)</span><input maxLength={24} value={details.coupon} placeholder="Enter your code" onChange={e=>change('coupon',e.target.value.toUpperCase())}/></label><p className="muted-text">A coupon discounts only its assigned honey size, even when your cart has other sizes.</p><button className="secondary-btn" disabled={busy}>{busy?'Checking…':'Review total & apply coupon'}</button>{error&&<p className="alert error" role="alert">{error}</p>}</fieldset></form></div><aside className="checkout-summary"><h2>Order summary</h2>{products.filter(p=>cart[p.id]).map(p=><div key={p.id}><span>{p.size_label} × {cart[p.id]}</span><strong>{currency(p.price*cart[p.id])}</strong></div>)}{quote?<><div><span>Subtotal</span><strong>{currency(quote.subtotal)}</strong></div><div><span>Discount{quote.coupon_code?' · '+quote.coupon_code:''}</span><strong>−{currency(quote.discount_amount)}</strong></div><div><span>Delivery</span><strong>{currency(quote.delivery_charge)}</strong></div><div className="total"><span>Total</span><strong>{currency(quote.grand_total)}</strong></div><button className="primary-btn" disabled={busy} onClick={place}>{busy?'Placing order…':'Place order'}</button><p className="muted-text">Payment is arranged offline.</p></>:<p>Enter your details and review the final server-checked total.</p>}</aside></section>}</>
}
export function MyOrders(){
 const {session}=useContext(Auth),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[page,setPage]=useState(0)
 useEffect(()=>{let live=true;setLoading(true);supabase.from('orders').select('*,order_items(*),invoices(*)').eq('customer_id',session.user.id).order('created_at',{ascending:false}).range(page*20,page*20+19).then(({data,error})=>{if(!live)return;if(error)setError(error.message);else {setOrders(data||[]);setError('')}setLoading(false)});return()=>{live=false}},[session.user.id,page])
 const invoice=async order=>{const {data,error}=await supabase.from('business_settings').select('*').eq('id',1).single();if(error){setError(error.message);return}const inv=Array.isArray(order.invoices)?order.invoices[0]:order.invoices;if(inv){const {downloadInvoicePdf}=await import('../lib/invoicePdf.js');downloadInvoicePdf({invoice:inv,order,settings:data})}}
 return <><div className="shop-heading"><span className="eyebrow">YOUR HONEY, ON ITS WAY</span><h1>My Orders</h1><p>Your current orders and past favourites.</p></div>{error&&<p className="alert error" role="alert">{error}</p>}{loading?<p>Loading orders…</p>:orders.length?orders.map(o=><article className="panel my-order" key={o.id}><div className="order-top"><div><strong>{o.order_number}</strong><p>{shortDate(o.created_at)}</p></div><span className="order-status">{o.status}</span></div>{o.order_items.map(i=><p key={i.id}>{i.product_name} · {i.size_label} × {i.quantity}</p>)}<p className="muted-text">{o.address}</p>{Number(o.discount_amount)>0&&<p>Coupon {o.coupon_code}: −{currency(o.discount_amount)}</p>}<div className="order-top"><strong>{currency(o.grand_total)}</strong><button className="secondary-btn" onClick={()=>invoice(o)}>Download invoice</button></div></article>):<section className="panel"><h2>No orders yet.</h2><Link className="primary-btn" to="/shop">Shop honey</Link></section>}<div className="button-group"><button className="text-btn" disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="text-btn" disabled={orders.length<20||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div></>
}
