import { useState } from 'react'
import { Link } from 'react-router-dom'
import { profitSummary } from '../lib/profit.js'
import { currency } from '../lib/format.js'
export default function ProfitSummary({data}){
 const [scope,setScope]=useState('delivered'),p=profitSummary(data,scope)
 const lines=[['Honey sales before discount',p.sales],['− Discounts given',-p.discount],['+ Delivery charged',p.delivery],['− Cost of sold honey',-p.cost],['− Free honey cost · '+p.freeJars+' jars',-p.freeCost],['− Operating expenses',-p.expense],['Net profit / loss',p.net]]
 return <section className="admin-card"><div className="section-heading"><div><h2>Complete profit calculation</h2><p>All-time business results, including free honey and expenses.</p></div><label className="field"><span>Sales included</span><select value={scope} onChange={e=>setScope(e.target.value)}><option value="delivered">Delivered orders</option><option value="all">All non-cancelled · estimated</option></select></label></div><div className="profit-breakdown"><div className="profit-result"><span>{scope==='all'?'Estimated net':'Net'} {p.net<0?'loss':'profit'}</span><strong>{currency(Math.abs(p.net))}</strong><p>{p.orders} {scope==='all'?'non-cancelled':'delivered'} orders. All recorded giveaways and active expenses deducted.</p><p>Free honey is deducted at actual cost, not selling price.</p></div><div className="profit-lines">{lines.map(([label,value])=><div key={label}><span>{label}</span><strong>{currency(value)}</strong></div>)}</div></div>{p.missingCost&&<p className="alert warning">Some sale or giveaway costs are zero / missing. Profit may be overstated. Use Edit on the original order or giveaway to correct its actual cost.</p>}<div className="profit-cash"><span>Net cash received: <strong>{currency(p.cashReceived)}</strong></span><span>Unsold stock at cost: <strong>{currency(p.stockValue)}</strong></span><Link to="/admin/expenses">Manage expenses →</Link></div><p className="muted-text">Cash received includes all payments less refunds and is separate from profit. Unsold stock is an asset; stock purchases are not deducted again as expenses. Do not count packaging twice if already included in jar cost.</p></section>
}
